name: Deploy to EC2

on:
  push:
    branches:
      - django-branch  # Trigger on push to the django-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST << 'EOF'
        # Update system and install Python and pip
        sudo yum update -y
        sudo yum install python3 python3-pip -y

        # Clone the repository if missing
        if [ ! -d "Projects-For-you" ]; then
            git clone https://github.com/hum1249/Projects-For-you.git
        fi
        cd Projects-For-you
        git checkout django-branch
        git pull origin django-branch

        # Create and activate the virtual environment named 'myenv'
        if [ ! -d "myenv" ]; then
            python3 -m venv myenv
        fi
        source myenv/bin/activate

        # Install dependencies
        pip install --upgrade pip
        pip install -r Bachha_project/requirements.txt

        # Start the Django development server
        cd Bachha_project
        echo "Starting the Django development server..."
        pkill -f runserver || true
        nohup python manage.py runserver 0.0.0.0:8000 > server.log 2>&1 &
        EOF
